### ISSUE TITLE
管理门户：界面没有当前登录用户的信息

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-MGMT-Web#2]
管理门户：界面没有当前登录用户的信息提示。

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：管理门户，界面显示当前登录用户的信息
2）、代码分支说明：https://github.com/AIPaaS/PaaS-FE-MGMT-Web.git   分支：develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无
@sunhongzhen
